# Generated by Django 5.2.3 on 2025-06-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memeber',
            new_name='Member',
        ),
    ]
