# Generated by Django 5.2.3 on 2025-06-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='FacultyModel',
        ),
    ]
